config/routes.rb
Rails.application.routes.draw do
 
  root 'pages#landing'

  devise_for :users

  resources :tracks
  resources :users , only: [:index, :edit, :update, :show]
  
  get 'privacy', to: 'pages#privacy'
  get 'activity',  to: 'activity#index'
  get 'about', to: 'pages#about'
  post 'search', to: 'tracks#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/role.rb
# == Schema Information
#
# Table name: roles
#
#  id            :bigint           not null, primary key
#  name          :string
#  resource_type :string
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  resource_id   :bigint
#
# Indexes
#
#  index_roles_on_name_and_resource_type_and_resource_id  (name,resource_type,resource_id)
#  index_roles_on_resource                                (resource_type,resource_id)
#
class Role < ApplicationRecord
  include PublicActivity::Model
  tracked
  
  validates :name, presence: true, uniqueness: true
  has_and_belongs_to_many :users, :join_table => :users_roles
  
  belongs_to :resource,
             :polymorphic => true,
             :optional => true
  

  validates :resource_type,
            :inclusion => { :in => Rolify.resource_types },
            :allow_nil => true

  scopify
end

app/models/track.rb
# == Schema Information
#
# Table name: tracks
#
#  id          :bigint           not null, primary key
#  description :text
#  language    :string           default("English"), not null
#  level       :string           default("Beginner"), not null
#  price       :integer          default(0), not null
#  short       :text
#  slug        :string
#  title       :string
#  created_at  :datetime         not null
#  updated_at  :datetime         not null
#  user_id     :bigint           not null
#
# Indexes
#
#  index_tracks_on_slug     (slug) UNIQUE
#  index_tracks_on_user_id  (user_id)
#
# Foreign Keys
#
#  fk_rails_...  (user_id => users.id)
#
class Track < ApplicationRecord
    extend FriendlyId
    include PublicActivity::Model
    tracked owner: Proc.new { |controller, model| controller.current_user }

    validates :title, presence: true
    validates :description, presence: true
    validates :short, presence: true
    validates :language, presence: true
    validates :level, presence: true
    validates :price, presence: true

    friendly_id :title, use: :slugged

    has_rich_text :description

    belongs_to :user
end

app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id                     :bigint           not null, primary key
#  current_sign_in_at     :datetime
#  current_sign_in_ip     :string
#  email                  :string           default(""), not null
#  encrypted_password     :string           default(""), not null
#  last_sign_in_at        :datetime
#  last_sign_in_ip        :string
#  remember_created_at    :datetime
#  reset_password_sent_at :datetime
#  reset_password_token   :string
#  sign_in_count          :integer          default(0), not null
#  slug                   :string
#  created_at             :datetime         not null
#  updated_at             :datetime         not null
#
# Indexes
#
#  index_users_on_email                 (email) UNIQUE
#  index_users_on_reset_password_token  (reset_password_token) UNIQUE
#  index_users_on_slug                  (slug) UNIQUE
#
class User < ApplicationRecord
  rolify
  extend FriendlyId
  include PublicActivity::Model
  tracked

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :trackable

  has_many :tracks

  friendly_id :email, use: :slugged

  after_create :assign_default_role

  validate :has_roles, on: :update

  def assign_default_role
    self.add_role(:student) if self.roles.blank?
    self.add_role(:teacher)
  end

  def username
    email
  end

  def has_roles
    if roles.blank?
      errors.add(:roles, 'Must contain at least 1 role')
    end
  end
end

app/controllers/activity_controller.rb
class ActivityController < ApplicationController
  def index
    @activities = PublicActivity::Activity.all.order(created_at: :desc)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    include PublicActivity::StoreController
    include Pundit

    rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

    before_action :set_global_variables, if: :user_signed_in?

    def set_global_variables
        @ransack_courses = Track.ransack(params[:courses_search], search_key: :courses_search)
    end

    private

        def user_not_authorized
            flash[:alert] = "You are not authorized to perform this action."
            redirect_to(request.referrer || root_path)
        end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def landing
    @popular = Track.limit(3)
    @recent = Track.last(3)
    @top = Track.limit(2)
  end

  def privacy
  end

  def about
  end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
  before_action :set_track, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, only: [:edit, :update, :destroy, :new, :create]

  layout 'courses'

  # GET /tracks
  # GET /tracks.json
  def index
    if params[:course]
      # @searched = params[:course]
      # @tracks = Track.where("title ILIKE ?", "%#{params[:course]}%")
      @q = Track.ransack(params[:course])
      @tracks = @q.result(distinct: true)
    else 
      @q = Track.ransack(params[:q])
      @tracks = @q.result(distinct: true)
    end
  end

  # GET /tracks/1
  # GET /tracks/1.json
  def show
  end

  # GET /tracks/new
  def new
    @track = Track.new
    authorize @track
    @levels = ['Beginner', 'Intermediate', 'Advanced']
    @languages = ['English', 'Russian', 'Spanish', 'German']
  end

  # GET /tracks/1/edit
  def edit
    authorize @track
  end

  # POST /tracks
  # POST /tracks.json
  def create
    @track = Track.new(track_params)
    authorize @track
    @track.user = current_user

    respond_to do |format|
      if @track.save
        format.html { redirect_to @track, notice: 'Track was successfully created.' }
        format.json { render :show, status: :created, location: @track }
      else
        format.html { render :new }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tracks/1
  # PATCH/PUT /tracks/1.json
  def update
    authorize @track
    respond_to do |format|
      if @track.update(track_params)
        format.html { redirect_to @track, notice: 'Track was successfully updated.' }
        format.json { render :show, status: :ok, location: @track }
      else
        format.html { render :edit }
        format.json { render json: @track.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tracks/1
  # DELETE /tracks/1.json
  def destroy
    authorize @track
    @track.destroy
    respond_to do |format|
      format.html { redirect_to tracks_url, notice: 'Track was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_track
      @track = Track.friendly.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def track_params
      params.require(:track).permit(:title, :description, :short, :language, :level, :price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update]
  def index
    @users = User.all
  end

  def edit
    authorize @user
  end

  def show
  end

  def edit
    @rolls = Role.all
  end

  def update
    authorize @user
    respond_to do |format|
      if @user.update(user_params)
         @user.create_activity key: 'user.edited_roles', owner: current_user
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        @rolls = Role.all
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  private

  def set_user
    @user = User.friendly.find(params[:id])
  end

  def user_params
    params.require(:user).permit({ role_ids: []})
  end
end

app/helpers/activity_helper.rb
module ActivityHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/active_storage/blobs/_blob.html.erb
<figure class="attachment attachment--<%= blob.representable? ? "preview" : "file" %> attachment--<%= blob.filename.extension %>">
  <% if blob.representable? %>
    <%= image_tag blob.representation(resize_to_limit: local_assigns[:in_gallery] ? [ 800, 600 ] : [ 1024, 768 ]) %>
  <% end %>

  <figcaption class="attachment__caption">
    <% if caption = blob.try(:caption) %>
      <%= caption %>
    <% else %>
      <span class="attachment__name"><%= blob.filename %></span>
      <span class="attachment__size"><%= number_to_human_size blob.byte_size %></span>
    <% end %>
  </figcaption>
</figure>

app/views/activity/index.html.haml
%h1 Activites
- @activities.each do |a|
    .row
        = a.id
        = a.trackable_type
        = a.trackable_id
        = a.key
        = a.parameters
        = time_ago_in_words(a.created_at)
        - if a.owner
            = a.owner.username

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Course</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'partials/navigation' %>
    <div class="container mt-2 app">
        <%= render 'partials/alerts' %>
        <div class="jumbotron">
            <h1 class="display-4">RailsCourse</h1>
            <p class="lead">A Udemy knockoff with Rails, yarn, webpack, puma, postgres</p>
            <hr class="my-4">
            <p>It uses utility classes for typography and spacing to space content out within the larger container.</p>
            <% unless current_user.nil? || policy(current_user).new? %>
            <%= link_to "New Course", new_track_path, class: 'btn btn-primary btn-lg' %>
            <% end %>
        </div>
        <%= yield %>
    </div>
    <%= render 'partials/footer' %>
</body>

</html>

app/views/layouts/courses.html.erb
<!DOCTYPE html>
<html>

<head>
    <title>Course</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_pack_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
    <%= render 'partials/navigation' %>
    <div class="container mt-2 app">
        <%= render 'partials/alerts' %>
        <%= yield %>
    </div>
    <%= render 'partials/footer' %>
</body>

</html>

app/views/pages/about.haml
%h1 About Me
%p I'm a developer

app/views/pages/landing.html.erb
<h2>Popular Courses</h2>
<%= render partial: 'tracks/track', collection: @popular %>
<hr />

<h2>Top Rated Courses</h2>
<%= render partial: 'tracks/track', collection: @top %>
<hr />

<h2>Most Recent Courses</h2>
<%= render partial: 'tracks/track', collection: @recent %>
<hr />

app/views/pages/privacy.html.erb
<h1>Privacy</h1>
<p>Find me in app/views/pages/privacy.html.erb</p>

app/views/partials/_alerts.html.erb
<% if notice %>
<p class="notice bg-success"><%= notice %></p>
<% end %>

<% if alert %>
<p class="alert bg-danger"><%= alert %></p>
<% end %>

app/views/partials/_footer.html.erb
<footer class="navigation-background">
    <%= link_to "RailsCourse", root_path %>
</footer>

app/views/partials/_navigation.html.erb
<nav class="navbar navbar-expand-lg navigation-background">
    <div class="container-fluid">
        <span class="navbar-brand mb-0 h1 text-light">
            <%= fa_icon 'graduation-cap' %>
            RailsCourse
        </span>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item">
                    <%= link_to root_path, class: 'nav-link active text-light' do %>
                    <%= fa_icon 'home' %>
                    <span>Home</span>
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to about_path, class: 'nav-link active text-light' do %>
                    <%= fa_icon 'laptop-code' %>
                    <span>About</span>
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to privacy_path, class: 'nav-link active text-light' do %>
                    <%= fa_icon 'user-secret' %>
                    <span>Privacy</span>
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to users_path, class: 'nav-link active text-light' do %>
                    <%= fa_icon 'user' %>
                    <span>Users</span>
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to activity_path, class: 'nav-link active text-light' do %>
                    <%= fa_icon 'user' %>
                    <span>Activity</span>
                    <% end %>
                </li>
                <li class="nav-item">
                    <%= link_to tracks_path, class: 'nav-link active text-light' do %>
                    <%= fa_icon 'school' %>
                    <span>Courses</span>
                    <% end %>
                </li>
                <% unless @ransack_courses.nil? %>
                <li class="nav-item">
                    <%= search_form_for @ransack_courses, url: tracks_path, local: true, class: 'form-inline my-2 my-lg-0' do |f| %>
                    <%= f.search_field :title_cont, placeholder: 'Search courses', class: 'form-control' %>
                    <%= f.submit 'Search', class: 'btn btn-outline-success ml-2 my-2 my-sm-0' %>
                    <% end %>
                </li>
                <% end %>
            </ul>

            <ul class="navbar-nav mr-right">
                <% if user_signed_in? %>
                <%= link_to "Account Settings #{current_user.email}", edit_user_registration_path, class: 'nav-link active text-light' %>
                <%= link_to "Sign Out", destroy_user_session_path, class: 'nav-link active text-light',  method: :delete %>
                <% else %>
                <%= link_to "Log In", new_user_session_path, class: 'nav-link active text-light' %>
                <%= link_to "Sign Up", new_user_registration_path, class: 'nav-link active text-light' %>
                <% end %>
            </ul>
        </div>
    </div>
</nav>

app/views/tracks/_form.html.haml
-# frozen_string_literal: true
= simple_form_for @track do |f|
  = f.error_notification
  = f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present?

  = f.input :title
  = f.rich_text_area :description
  = f.input :short
  = f.input :language, collection: @languages
  = f.input :level, collection: @levels
  = f.input :price
  = f.button :submit, class: 'btn btn-primary mt-3'

app/views/tracks/_track.html.haml
%div.card.mb-5
    %div.card-header
        = fa_icon 'school'
        = link_to "#{track.title}", track
    %div.card-body #{track.description}
    %div.card-body 
        %h5
            = track.short
    %div.card-footer
        %span.track-detail
            = fa_icon 'language' 
            = track.language
        %span.track-detail
            = fa_icon 'signal'
            = track.level
        %span.track-detail
            = number_to_currency(track.price)
    %div.card-footer.text-muted 
        %p 
            = fa_icon 'clock'
            #{track.created_at}
        %p 
            = fa_icon 'inbox'
            #{track.user.email}

app/views/tracks/edit.html.haml
%h1 Editing track

= render 'form'

= link_to 'Show', @track

app/views/tracks/index.html.haml
- if @searched
  %h1 Searched for #{@searched}
%div.row
  .col-md-2
    = search_form_for @q do |form|
      %div.form-group
        = form.label :title
        = form.search_field :title_cont
      %div.form-group
        = form.label :description
        = form.search_field :description_cont
      %div.form-group
        = form.label :level
        = form.search_field :level_cont
      %div.form-group
        = form.label :language
        = form.search_field :language_cont
      %div.form-group
        = form.label :teacher
        = form.search_field :user_email_cont
      %div.form-group
        = form.button :submit, class: 'btn btn-primary mt-3'
  .col-md-10
    %table.table
      %thead
        %tr
          %th= sort_link(@q, :title)
          %th= sort_link(@q, :description)
          %th Teacher
          %th= sort_link(@q, :level)
          %th= sort_link(@q, :language)
          %th= sort_link(@q, :price)
          %th
          %th
          %th
      %tbody
        - @tracks.each do |track|
          %tr
            %td= track.title
            %td= track.description
            %td= track.user.email
            %td= track.level
            %td= track.language
            %td= number_to_currency(track.price)
            %td= link_to 'Show', track, class: 'btn btn-primary' 
            - if policy(track).edit?
              %td= link_to 'Edit', edit_track_path(track), class: 'btn btn-primary'
            - if policy(track).destroy?
              %td= link_to 'Destroy', track, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' if policy(track).destroy?

app/views/tracks/new.html.haml
%h1 New track

= render 'form'

app/views/tracks/show.html.haml
%p#notice= notice

= render 'track', track: @track

%p
  %b Title:
  = @track.title
%p
  %b Description:
  = @track.description

- if policy(@track).edit?
  = link_to 'Edit', edit_track_path(@track)

app/views/users/_track.html.haml
%li.list-group-item 
    = fa_icon 'school'
    = link_to track.title, track

app/views/users/_user.html.haml
%div.card.mb-5
    %div.card-header
        = fa_icon 'user'
        = link_to user.email, user
    %div.card-body 
        %p Courses #{user.tracks.count}
        %ul.list-group.list-group-flush
            = render partial: 'users/track', collection: user.tracks
    - unless user.roles.empty?
        %div.card-footer
            - user.roles.each do |role|
                %span.badge.badge-pill.badge-primary
                    = role.name
    %div.card-footer.text-muted 
        %p 
            = time_ago_in_words(user.created_at)
        %p 
            = user.current_sign_in_ip

app/views/users/edit.html.haml
%h1
    = "Editing #{@user.email}"
    
= simple_form_for @user do |f|
    = f.collection_check_boxes :role_ids, @rolls, :id, :name
    = f.error :roles, class: 'text-danger'
    %hr
    = f.submit 'Update', class: 'btn btn-primary'

app/views/users/index.html.haml
= render @users

app/views/users/show.html.haml
%div.card.mb-5
    %div.card-header
        = fa_icon 'user'
        = link_to "#{@user.email}", edit_user_path(@user)
    %div.card-body 
        %p Courses #{@user.tracks.count}
        %ul.list-group.list-group-flush
            = render partial: 'users/track', collection: @user.tracks
    - unless @user.roles.empty?
        %div.card-footer
            - @user.roles.each do |role|
                %span.badge.badge-pill.badge-primary
                    = role.name
    %div.card-footer.text-muted 
        %p 
            = time_ago_in_words(@user.created_at)
        %p 
            = @user.current_sign_in_ip
        %p
            = link_to 'Edit Roles', edit_user_path(@user), class: 'btn btn-primary'